insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("SAMSUNG_TV", "가전제품", 13450000, "삼성", 34, "신제품")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("아이폰12", "전자기기", 1450000, "애플", 23, "청년들의 감성을 자극한 디자인 ")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("LG냉장고", "가전제품", 15000000, "엘지", 132, "저장 공간이 세계 제일")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("다이슨 청소기", "가전제품", 1055000, "다이슨", 4, "가장 강력한 흡입력")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("김치냉장고", "가전제품", 13450000, "엘지", 32, "최고의 신선함 유지")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("공기청정기", "가전제품", 13450000, "삼성", 15, " 신속관리")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("마우스", "전자기기", 40000, "삼성", 121, "가성비에 좋다")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("LG그램", "전자기기", 1450000, "엘지", 119, "깃털 같은 가벼움")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("스피커", "가전제품", 1000000, "야마하", 916, "엄청난 출력")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("에어드레서", "가전제품", 33450000, "엘지", 624, "똑똑한 옷장")
